jenkins

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -96,6 +96,7 @@ pipeline {
                 script{
                     sh """
                         echo "building"
+                        exit 1
                     """
                 }
             }
@@ -128,6 +129,10 @@ pipeline {
         success {
             echo "pipeline success"
         }
+        failure {
+            echo "pipeline failure"
+        }
+    
     
     }
 }
